
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 配置eureka服务地址
server:
  port: 8763
spring:
  application:
    name: service-jiangxl  # 为你的应用起个名字，该名字将注册到eureka注册中心
